export default {
    Template: {
        CustomerId: 1,
        IsWe: true,
        Description: '2',
        IsEnabled: true,
        IsDeleted: false,
    },
    Countries: [
        {
            CountryName: '111',
            RegionalShippingViews: [
                {
                    CountryName: 0,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 839,
                },
                {
                    CountryName: 1,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AE',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 840,
                },
                {
                    CountryName: 2,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AK',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 841,
                },
                {
                    CountryName: 3,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AL',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 842,
                },
                {
                    CountryName: 4,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AP',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 843,
                },
                {
                    CountryName: 5,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AR',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 844,
                },
                {
                    CountryName: 6,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AS',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 845,
                },
                {
                    CountryName: 7,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_AZ',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 846,
                },
                {
                    CountryName: 8,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_CA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 847,
                },
                {
                    CountryName: 9,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_CO',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 848,
                },
                {
                    CountryName: 10,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_CT',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 849,
                },
                {
                    CountryName: 11,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_DC',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 850,
                },
                {
                    CountryName: 12,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_DE',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 851,
                },
                {
                    CountryName: 13,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_FL',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 852,
                },
                {
                    CountryName: 14,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_GA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 853,
                },
                {
                    CountryName: 15,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_GU',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 854,
                },
                {
                    CountryName: 16,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_HI',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 855,
                },
                {
                    CountryName: 17,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_IA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 856,
                },
                {
                    CountryName: 18,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_ID',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 857,
                },
                {
                    CountryName: 19,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_IL',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 858,
                },
                {
                    CountryName: 20,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_IN',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 859,
                },
                {
                    CountryName: 21,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_KS',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 860,
                },
                {
                    CountryName: 22,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_KY',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 861,
                },
                {
                    CountryName: 23,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_LA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 862,
                },
                {
                    CountryName: 24,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 863,
                },
                {
                    CountryName: 25,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MD',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 864,
                },
                {
                    CountryName: 26,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_ME',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 865,
                },
                {
                    CountryName: 27,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MI',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 866,
                },
                {
                    CountryName: 28,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MN',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 867,
                },
                {
                    CountryName: 29,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MO',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 868,
                },
                {
                    CountryName: 30,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MP',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 869,
                },
                {
                    CountryName: 31,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MS',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 870,
                },
                {
                    CountryName: 32,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_MT',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 871,
                },
                {
                    CountryName: 33,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NC',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 872,
                },
                {
                    CountryName: 34,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_ND',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 873,
                },
                {
                    CountryName: 35,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NE',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 874,
                },
                {
                    CountryName: 36,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NH',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 875,
                },
                {
                    CountryName: 37,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NJ',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 876,
                },
                {
                    CountryName: 38,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NM',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 877,
                },
                {
                    CountryName: 39,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NV',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 878,
                },
                {
                    CountryName: 40,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_NY',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 879,
                },
                {
                    CountryName: 41,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_OH',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 880,
                },
                {
                    CountryName: 42,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_OK',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 881,
                },
                {
                    CountryName: 43,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_OR',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 882,
                },
                {
                    CountryName: 44,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_PA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 883,
                },
                {
                    CountryName: 45,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_RI',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 884,
                },
                {
                    CountryName: 46,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_SC',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 885,
                },
                {
                    CountryName: 47,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_SD',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 886,
                },
                {
                    CountryName: 48,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_TN',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 887,
                },
                {
                    CountryName: 49,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_TX',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 888,
                },
                {
                    CountryName: 50,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_UT',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 889,
                },
                {
                    CountryName: 51,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_VA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 890,
                },
                {
                    CountryName: 52,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_VT',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 891,
                },
                {
                    CountryName: 53,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_WA',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 892,
                },
                {
                    CountryName: 54,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_WI',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 893,
                },
                {
                    CountryName: 55,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_WV',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 894,
                },
                {
                    CountryName: 56,
                    RegionalShippingViews: [],
                    CustomerId: 1,
                    TemplateId: 9,
                    CountryCode: 'US_WY',
                    Type: 5,
                    ShippingPrice: null,
                    LocalShippingPrice: null,
                    IsEnabled: true,
                    IsDeleted: false,
                    Id: 895,
                },
            ],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        {
            CountryName: '111',
            RegionalShippingViews: [],
            CustomerId: 1,
            TemplateId: 9,
            CountryCode: 'US',
            Type: 2,
            ShippingPrice: 11,
            LocalShippingPrice: null,
            IsEnabled: true,
            IsDeleted: false,
            Id: 838,
        },
        
    ],
};